# Generated by Django 5.0.2 on 2024-02-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='description',
        ),
        migrations.RemoveField(
            model_name='track',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='url',
        ),
    ]
