# Generated by Django 5.0.2 on 2024-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_img_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.FileField(
                blank=True, null=True, upload_to="categories/images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.FileField(blank=True, null=True, upload_to="products/images"),
        ),
    ]
