# Generated by Django 5.0.2 on 2024-02-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_img_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/images"
            ),
        ),
    ]
